### ISSUE TITLE
Need to allow whitespace in quoted string values

### ISSUE THREAD

**Issue by y-tang** [almeida/redis-mass#4]
When inserting into Redis, sometimes the value is a json blob. There will be whitespaces in quoted strings in the json blob. For example:
```
SET redisKey {"json key 1":"value 1"}
```

Currently, this would produce
```
*6
$3
SET
$8
redisKey
$6
{"json
$3
key
$9
1":"value
$3
1"}
```

Instead, we want
```
*3
$3
SET
$8
redisKey
$24
{"json key 1":"value 1"}
```

Here is a PR #3 to allow whitespaces in quoted strings

**Comment by almeida** [comment]
PR accepted. Thanks @y-tang.
